GNUSTEP_MAKEFILES=/GNUstep/System/Library/Makefiles

include $(GNUSTEP_MAKEFILES)/common.make

APP_NAME = NSWindowNSButton NSMenuItem

NSWindowNSButton_OBJC_FILES = NSWindowNSButton.m
NSMenuItem_OBJC_FILES = NSMenuItem.m

# Uncomment the following if you have an icon
#MyFirstApp_APPLICATION_ICON = MyApp.png
#MyFirstApp_RESOURCE_FILES = MyApp.png

include $(GNUSTEP_MAKEFILES)/application.make