GNUSTEP_MAKEFILES=/GNUstep/System/Library/Makefiles
include $(GNUSTEP_MAKEFILES)/common.make

CC = clang
APP_NAME = FirstGUIApp SecondGUIApp
FirstGUIApp_OBJC_FILES = FirstGUIAppAppDelegate.m
SecondGUIApp_OBJC_FILES = FirstGUIAppAppDelegate_eg2.m

# uncomment the following if you have an icon
#FirstGUIApp_APPLICATION_ICON = MyApp.png
#FirstGUIApp_RESOURCE_FILES = MyApp.png

include $(GNUSTEP_MAKEFILES)/application.make