GNUSTEP_MAKEFILES=/GNUstep/System/Library/Makefiles

include $(GNUSTEP_MAKEFILES)/common.make

APP_NAME = HelloworldGUI

HelloworldGUI_HEADERS = AppController.h
HelloworldGUI_OBJC_FILES = main.m AppController.m
HelloworldGUI_RESOURCE_FILES = HelloworldGUIInfo.plist

# Uncomment the following if you have an icon
#MyFirstApp_APPLICATION_ICON = MyApp.png
#MyFirstApp_RESOURCE_FILES = MyApp.png

include $(GNUSTEP_MAKEFILES)/application.make